name: AWS Deployment
on: 
  pull_request:
    branches:
    - 34-host-on-aws
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{secrets.TOKEN}}
        AWS_PEM: ${{secrets.AWS_WEB_HOSTING_KEY_PEM}}
        AWS_NAME: ${{secrets.INSTANCE_DNS}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: ssh into instance
        run: ssh -v -o StrictHostKeyChecking=no -i $AWS_PEM ubuntu@$INSTANCE_DNS
                
      - name: git pull
        run: |
          cd ~/ECE46100-phase-2
          git checkout 34-host-on-aws
          git pull
          
      - name: restart nginx
        run: |
          sudo systemctl restart nginx
          sudo nginx -t
